# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Strap Technical Research
email: mail@strapdev.com
description: > # this means to ignore newlines until "baseurl:"
  Strap Technical Research, the online playground of Charles Lam, digital product designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.strapdev.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

